### ISSUE TITLE
Online access maybe broken?

### ISSUE THREAD

**Issue by mhepaixao** [sotorrent/db-scripts#5] opened 2018-10-30 18:45 UTC
Hi,

My name is Matheus Paixao, a research assistant at State University of Ceara, Brazil. When trying to access the latest Google BigQuery version of the dataset, as provided in the SOTorrent website (https://bigquery.cloud.google.com/dataset/sotorrent-org:2018_09_23) I get a the following message:

"Unable to find dataset: sotorrent-org:2018_09_23". 

I've tried different browsers and different internet connections, but still, same error message. 

Is that only for me? Or am I doing something wrong?

Cheers,
Matheus

**Comment by sbaltes** [comment] 2018-10-30 19:25
Hi! Did you follow the [tutorial](https://cloud.google.com/blog/products/gcp/how-to-run-a-terabyte-of-google-bigquery-queries-each-month-without-a-credit-card) linked on the [project page](http://empirical-software.engineering/projects/sotorrent/) to activate BigQuery access for your Google account?

**Comment by mhepaixao** [comment] 2018-10-31 13:28
Hi,

I did follow the tutorial, and still, I see this problem. A colleague of mine managed to access the online version with no problem whatsoever though. There seems to be a problem with my google account, it's the only explanation.

Thank you for the quick response. I'll let to your own decision whether this issue is closed or not :-D

Cheers,
Matheus

**Comment by sbaltes** [comment] 2018-11-02 00:32
Thanks for the update. I'll close this issue, because the problem doesn't seem to be caused by the dataset. If you'll find out what caused the issue, feel free to comment here again so that others can see it.

**Closed as completed by sbaltes** 2018-11-02 00:32 UTC
Labels: help wanted

**Comment by WilliamGoss** [comment] 2018-11-21 21:00
Hello, I followed the tutorial and setup a Google Cloud Platform account, but when clicking the link for the data, it's still saying it's unable to be found. I tried with two different Google accounts and three different browsers, but no dice. Any ideas what next steps I should try?

**Comment by sbaltes** [comment] 2018-11-28 16:30
To everyone having similar issues:

* Try disabling your ad blocker.
* Disable and re-enable the BigQuery API in the Google Cloud Console. 
* Please also check out the [BigQuery Beta](https://console.cloud.google.com/bigquery?p=sotorrent-org&d=2018_09_23&t=PostReferenceGH&page=table) and comment here if the _"Unable to find dataset"_ error also occurs there.
